apiVersion: v1
kind: Service
metadata:
  name: movie-name-generator
spec:
  selector:
    app: movie-name-generator
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080